import { Car, Search, Users, Home, MessageCircle, Banknote, Smartphone, GitBranch, Database, Zap, Shield, Activity, Cpu, TrendingUp, Clock, Globe, BarChart3 } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const carChoiceConfig: CaseStudyConfig = {
  slug: "car-choice",
  icon: <Car size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "iOS + Android" },
    { icon: <Users size={12} />, text: "Buyers + Dealers" },
    { icon: <Clock size={12} />, text: "6 Months" },
    { icon: <MessageCircle size={12} />, text: "Stream Chat" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "flow", label: "Flow" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-orange-800/20",
    accentVia: "via-background",
    accentTo: "to-amber-500/5",
    primary: "#C2410C",
    primaryFaded: "from-orange-800/10",
  },
  storyTitle: "Buying a used car in India means visiting five different platforms.",
  storyBody: "Listings on one site, prices on another, comparisons on a third, loans at a bank, and dealers reached by phone. No single mobile experience combines discovery, specifications, real-time dealer communication, financing, and selling into one seamless flow.",
  storyCoda: "We built the missing layer.",
  flowTitle: "How a Purchase Moves",
  flowSteps: [
    { label: "Buyer", icon: <Users size={16} /> },
    { label: "Browse & Filter", icon: <Search size={16} /> },
    { label: "Compare Cars", icon: <Car size={16} /> },
    { label: "Chat Dealer", icon: <MessageCircle size={16} /> },
    { label: "Finance & Insurance", icon: <Banknote size={16} /> },
    { label: "Book & Purchase", icon: <Home size={16} /> },
  ],
  features: [
    {
      id: "browse", number: "01", icon: <Search size={14} />, label: "Smart Browsing", title: "Multi-Attribute Car Discovery",
      tagline: "Find any used car across 6 filter dimensions",
      problem: "Car buyers in India browse across multiple platforms — one for listings, another for prices, a third for comparisons. No single app combines filtering, browsing, and city-based discovery.",
      solution: "A home screen combining banner carousels, brand grids (5-column), city-based browsing (11 Indian cities), and infinite-scroll results grid (6 items per batch). Multi-attribute filters (brand, budget, fuel, transmission, color) via bottom sheet with searchable FlatLists. Location-aware personalization via GPS detection persisted to AsyncStorage.",
      metrics: "6 filter dimensions | 11 cities | 6 items/batch",
    },
    {
      id: "detail", number: "02", icon: <Car size={14} />, label: "Car Details", title: "Everything About a Used Car",
      tagline: "Gallery, specs, features, and dealer info in one scroll",
      problem: "Car detail pages typically show specs in one place, photos in another, and dealer info requires a separate navigation step — breaking the browsing flow.",
      solution: "A comprehensive detail screen with Reanimated-powered image carousel (auto-play, gesture snapping), 12 attribute display (reg year, insurance, fuel, seats, KMs, RTO, ownership, engine, transmission, make year, color, last updated), FeaturesAccordion and SpecsAccordion as tabbed bottom sheets, EMI calculator via RBSheet, and native share sheet integration.",
      metrics: "12 attributes | Reanimated carousel | 2 accordion types",
    },
    {
      id: "chat", number: "03", icon: <MessageCircle size={14} />, label: "Real-Time Chat", title: "Stream Chat Integration",
      tagline: "Buyers and dealers connect instantly",
      problem: "Enquiry forms create asynchronous communication — dealers respond hours later if at all. WhatsApp mixing personal and business conversations is unprofessional.",
      solution: "Stream Chat with server-generated tokens via POST /api/generate-chat-token. Deterministic channel creation (chat-{seller}-{buyer}-{car}) prevents duplicates. Tapping Chat Now creates a backend lead + opens a chat room in one flow. First message auto-sent with buyer contact details. All/Unread tabs, Today/Older grouping, profile initials fallback.",
      metrics: "Deterministic channels | Server tokens | Auto-first message",
    },
    {
      id: "sell", number: "04", icon: <Home size={14} />, label: "Sell Wizard", title: "3-Step Vehicle Listing",
      tagline: "List your car in under 5 minutes",
      problem: "Listing a used car requires filling long forms with 20+ fields — most sellers abandon before completing.",
      solution: "A guided 3-step wizard using react-native-progress-steps. Step 1: Brand → Model → Variant cascading + City → State → Pincode + Color. Step 2: Price, Insurance, KMs, Fuel, Year, Registration, Ownership, Transmission. Step 3: Multi-image upload with preview and delete. Per-step progressive validation catches errors early.",
      metrics: "3 steps | 20+ fields | Progressive validation",
    },
    {
      id: "dealer", number: "05", icon: <Users size={14} />, label: "Dealer Platform", title: "Dealer Registration & Management",
      tagline: "From registration to lead management",
      problem: "Dealers need a professional presence on the platform — business verification, brand portfolio display, and a way to receive and manage buyer enquiries.",
      solution: "Dealer registration with business name, WhatsApp validation, multi-brand selection (searchable MultiSelect with logos), city/state/pincode, office photo upload, and business document upload. Dealer profile displays business info, brand logos, office photos, and car inventory. Buyers view dealer profiles from car detail pages.",
      metrics: "Multi-brand select | Document upload | Office photos",
    },
    {
      id: "finance", number: "06", icon: <Banknote size={14} />, label: "Financing", title: "Loans, Insurance & EMI Calculator",
      tagline: "From browsing to financing in one flow",
      problem: "Car financing requires separate visits to banks. Research on one app, loans on another, EMI on a third — causing 40%+ drop-off.",
      solution: "Car loan applications to 6 partner banks (Axis, HDB, ICICI, IDFC, TVS Credit, Yes Bank) with logos. Insurance enquiry with DateTimePicker. EMI calculator with debounced sliders (12-84 months, 1-15% interest). All forms use Formik + Yup with cascading dropdown pattern (Brand → Model → Variant).",
      metrics: "6 partner banks | Formik + Yup | 3 EMI sliders",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 18, suffix: "", label: "Screens", sublabel: "Across 2 nav groups", color: "text-accent" },
    { icon: <GitBranch size={16} />, value: 21, suffix: "", label: "Components", sublabel: "Reusable design system", color: "text-emerald-400" },
    { icon: <Database size={16} />, value: 30, suffix: "+", label: "API Endpoints", sublabel: "Laravel REST API", color: "text-accent" },
    { icon: <Users size={16} />, value: 2, suffix: "", label: "User Types", sublabel: "Buyers and dealers", color: "text-cyan-400" },
    { icon: <MessageCircle size={16} />, value: 1, suffix: "", label: "Chat Service", sublabel: "Stream Chat integrated", color: "text-emerald-400" },
    { icon: <Globe size={16} />, value: 11, suffix: "", label: "Cities", sublabel: "Indian cities supported", color: "text-accent" },
  ],
  timelineTitle: "6 phases across 6 months",
  timeline: [
    { phase: "1", title: "Discovery & Research", desc: "Competitor analysis, user interviews with buyers and dealers, feasibility study" },
    { phase: "2", title: "Architecture & Design", desc: "Navigation tree, component library, design system, API contract design" },
    { phase: "3", title: "Core Build", desc: "Auth (email/password + Google OAuth), Home screen, Car Details, Brand/City browsing" },
    { phase: "4", title: "Engagement Features", desc: "Stream Chat integration, Sell wizard, My Vehicles dashboard" },
    { phase: "5", title: "Service Features", desc: "Car loan (6 banks), Insurance, Dealer registration, EMI calculator" },
    { phase: "6", title: "Quality & Launch", desc: "Cross-device testing, edge case handling, performance optimization, EAS Build" },
  ],
  decisions: [
    {
      title: "Stream Chat over custom WebSocket",
      icon: <MessageCircle size={16} />,
      alternatives: "Custom Socket.IO, Firebase Realtime Database",
      tradeoff: "Third-party dependency with ongoing API costs vs 6+ weeks of custom chat development for feature parity.",
      decision: "Stream Chat provides real-time messaging, read receipts, push notifications, offline support, and message history out of the box. Server-generated tokens ensure security. Deterministic channel IDs prevent duplicates.",
      impact: "6+ weeks saved vs custom build. Production-grade chat with zero ongoing maintenance.",
    },
    {
      title: "Email/Password + Google OAuth over phone-only OTP",
      icon: <Smartphone size={16} />,
      alternatives: "Phone-only OTP, Magic link email",
      tradeoff: "Email/password is less common in Indian mobile apps where phone numbers are the primary identifier. SMS OTP has 5-30 second delivery delays.",
      decision: "Email/password as primary for sub-second authentication. Google OAuth via expo-auth-session as convenience option. Phone OTP available as fallback during signup.",
      impact: "Sub-second auth at first impression. Familiar login for users who prefer Google. Phone OTP fallback.",
    },
    {
      title: "Formik + Yup over raw useState forms",
      icon: <Database size={16} />,
      alternatives: "react-hook-form, raw useState",
      tradeoff: "Formik re-renders on every field change, which can impact performance on forms with 20+ fields across 3 steps.",
      decision: "Formik for 6 major forms (sell, edit, loan, insurance, dealer reg, signup) with Yup validation schemas. Raw useState for 2 simple forms. Per-step rendering in sell wizard isolates re-renders to active step.",
      impact: "Consistent form handling across 6 forms. Schema-based validation. No performance issues due to step isolation.",
    },
    {
      title: "Reanimated Carousel over FlatList galleries",
      icon: <Zap size={16} />,
      alternatives: "FlatList paging, react-native-snap-carousel",
      tradeoff: "Additional dependency with specific version requirements. Manual FlatList is zero-dependency but lacks auto-play and smooth gestures.",
      decision: "react-native-reanimated-carousel provides auto-play (3s interval), gesture-driven snapping, loop support, and Expo SDK 54 compatibility.",
      impact: "60fps image galleries with auto-play. Smooth gesture snapping. Full Expo SDK compatibility.",
    },
  ],
  challenges: [
    {
      icon: <GitBranch size={16} />, label: "Cascading Dependent Dropdowns",
      problem: "Brand → Model → Variant and City → State → Pincode each require 3 sequential API calls. Users can change any level at any time, requiring downstream state cleanup.",
      solution: "Guarded useEffect chains: mount fetches brands + cities → brand select triggers model fetch → model select triggers variant fetch. Loading states per dependency level. State cleanup on selection change clears downstream values.",
      result: "Clean cascading across 4+ forms. Zero stale data from race conditions.",
      metrics: ["4+ form screens", "3 dependency levels", "Guarded effects"],
    },
    {
      icon: <MessageCircle size={16} />, label: "Real-Time Chat + Lead Generation",
      problem: "Tapping Chat Now must create a backend lead and a Stream Chat channel atomically. If either fails, the user ends up in an inconsistent state.",
      solution: "Single API call (POST /api/bookvehiclenow) creates the backend lead. Client-side createOrGetChannel creates a deterministic Stream channel. First message auto-sent with buyer contact details. Retry button if channel creation fails.",
      result: "Atomic lead + channel creation. Zero orphaned channels. Reliable first-contact flow.",
      metrics: ["Atomic creation", "Auto-first message", "Retry support"],
    },
    {
      icon: <Database size={16} />, label: "Image Management (Upload/Delete)",
      problem: "Editing vehicles mixes local uploads (file:// URIs) with existing server images (https:// URLs). Deleting requires distinguishing between the two.",
      solution: "URI prefix check determines behavior: file:// URIs removed from local array only; https:// URIs trigger DELETE API call before removal. Array tracks string URIs. JSON-safe parsing with fallback for API response strings.",
      result: "Reliable image editing. Zero accidental server deletions of new uploads.",
      metrics: ["URI prefix check", "DELETE API call", "JSON-safe parsing"],
    },
    {
      icon: <Users size={16} />, label: "Multi-Role UX Across 18 Screens",
      problem: "Buyers and Dealers see different dashboards, CTAs, and permissions. Building separate flows would double the codebase.",
      solution: "Single usertype field drives conditional rendering everywhere: dynamic signup, role-aware Home, conditional Edit Vehicle for owners, different Chat channel sets per role.",
      result: "Tailored experiences from one codebase. Zero duplication across roles.",
      metrics: ["18 screens", "1 usertype field", "Conditional rendering"],
    },
  ],
  techStackTitle: "The tools and frameworks powering Carz Choice",
  techStack: [
    { name: "React Native (Expo)", cat: "Mobile", desc: "Cross-platform iOS/Android with Expo Router for file-based navigation and 21 reusable components forming a complete design system." },
    { name: "Laravel PHP", cat: "Backend", desc: "REST API with Sanctum auth, Validator for field-level error messages, and 30+ endpoints serving vehicle, user, and lead data." },
    { name: "Stream Chat", cat: "Real-Time", desc: "Managed chat service for dealer-buyer messaging with server-generated tokens, deterministic channel IDs, read receipts, and offline support." },
    { name: "MySQL", cat: "Database", desc: "Relational data store for vehicles, users, dealers, leads, loan enquiries, and insurance requests with JSON columns for flexible attributes." },
    { name: "NativeWind", cat: "UI", desc: "Tailwind CSS utility classes for React Native. Build-time generation via Babel plugin eliminates runtime CSS-in-JS overhead across 21 components." },
    { name: "Formik + Yup", cat: "Forms", desc: "Schema-based form management across 6 major forms with field-level validation, error state tracking, and consistent submission handling." },
    { name: "Reanimated", cat: "Animations", desc: "Native-driven animations for image carousels with auto-play, gesture snapping, and 60fps transitions during gallery interaction." },
    { name: "React Context", cat: "State", desc: "LocationContext (current city) and ChatContext (Stream client) provide global state without Redux. AsyncStorage persists auth tokens and city preference." },
  ],
  resultsTitle: "Measurable impact from architectural decisions",
  results: [
    { icon: <Smartphone size={20} />, metric: "18", label: "App Screens", desc: "Organized into 2 nav groups (auth, root) with Expo Router file-based routing across tabs and stacked screens." },
    { icon: <GitBranch size={20} />, metric: "21", label: "Reusable Components", desc: "Complete design system: 6 card variants, 2 accordion types, 2 gallery components, 5+ forms, map/modal utilities." },
    { icon: <Database size={20} />, metric: "30+", label: "API Endpoints", desc: "Laravel REST API with Sanctum auth, field-level errors, and consistent patterns across vehicle, user, lead, and finance domains." },
    { icon: <MessageCircle size={20} />, metric: "Stream Chat", label: "Real-Time Messaging", desc: "Server-generated tokens, deterministic channels, auto-first message, All/Unread tab filtering." },
    { icon: <Users size={20} />, metric: "2", label: "User Types", desc: "Buyers and dealers from one codebase. Conditional rendering via usertype field across all 18 screens." },
    { icon: <BarChart3 size={20} />, metric: "6", label: "Partner Banks", desc: "Integrated loan application flow for Axis, HDB, ICICI, IDFC, TVS Credit, and Yes Bank." },
  ],
  lessons: [
    { title: "Centralize the API layer into a single Axios instance with interceptors", what: "Create a single Axios instance with request interceptors for auth headers and response interceptors for 401 handling and data normalization.", why: "Each screen handles try-catch, token injection, and error toasts independently. A centralized instance would eliminate ~15 lines of duplicated code per screen.", impact: "Would remove ~300 lines of duplicated HTTP handling across 18 screens and guarantee consistent 401 redirect behavior." },
    { title: "Add offline-first support with SQLite caching", what: "Local SQLite cache for recently viewed cars and cached search results, with background sync when connectivity returns.", why: "Car buyers often browse on the go with unreliable connectivity. AsyncStorage is synchronous and blocks the JS thread.", impact: "Would improve perceived load time by 50% for repeat views and enable full offline browsing." },
    { title: "Abstract the cascading picker pattern into a reusable hook", what: "Extract Brand → Model → Variant cascading into a useCascadingPicker hook managing the fetch chain, state resets, and loading indicators.", why: "Currently each form duplicates the useEffect chain for the same pattern appearing in 4+ forms.", impact: "Would reduce form code by ~40 lines per form and eliminate risk of missing state cleanup." },
  ],
  cta: {
    href: "/projects/victory-vision",
    icon: <Cpu size={24} />,
    title: "Victory Vision",
    subtitle: "Fantasy Sports Intelligence",
    description: "AI-powered fantasy sports companion with team generation, screenshot analysis, match predictions, and performance tracking. Built with React Native (Expo SDK 53).",
  },
};
