import { Car, Search, Users, Home, MessageCircle, Banknote, Smartphone, GitBranch, Database, Zap, Shield, Activity, Cpu, TrendingUp, Clock, Globe, BarChart3 } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const carzchoiceOldAppConfig: CaseStudyConfig = {
  slug: "carzchoice-old-app",
  icon: <Smartphone size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "Android" },
    { icon: <Users size={12} />, text: "P2P Marketplace" },
    { icon: <Clock size={12} />, text: "3 Months" },
    { icon: <MessageCircle size={12} />, text: "Direct Chat" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "flow", label: "Flow" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-sky-800/20",
    accentVia: "via-background",
    accentTo: "to-blue-500/5",
    primary: "#0369A1",
    primaryFaded: "from-sky-800/10",
  },
  storyTitle: "Selling a used car means dealing with dealers, paperwork, and waiting.",
  storyBody: "What if selling your old car was as simple as posting a photo and a price? No dealer commissions, no financing pitches, no EMI calculators — just a straightforward peer-to-peer marketplace where owners list their cars and buyers contact them directly. Like OLX, but purpose-built for cars.",
  storyCoda: "We stripped away everything except the transaction.",
  flowTitle: "How a Deal Moves",
  flowSteps: [
    { label: "Seller", icon: <Users size={16} /> },
    { label: "List Car", icon: <Car size={16} /> },
    { label: "Browse & Filter", icon: <Search size={16} /> },
    { label: "Chat Buyer", icon: <MessageCircle size={16} /> },
    { label: "Negotiate", icon: <Banknote size={16} /> },
    { label: "Sold!", icon: <Home size={16} /> },
  ],
  features: [
    {
      id: "browse", number: "01", icon: <Search size={14} />, label: "Browse Listings", title: "Simple Car Browsing",
      tagline: "Filter by budget, brand, fuel, and location",
      problem: "Car listing apps overwhelm users with dealer promotions, featured listings, and financing offers. Sellers want their cars seen; buyers want a clean list.",
      solution: "A clean, OLX-style listing page with basic filters (budget, brand, fuel type, city). Grid layout shows car photo, name, price, year, and location. No promoted listings, no distracting banners.",
      metrics: "4 filter types | Grid layout | Zero promotions",
    },
    {
      id: "detail", number: "02", icon: <Car size={14} />, label: "Car Details", title: "Quick Vehicle View",
      tagline: "Photos, price, and seller info at a glance",
      problem: "Car detail pages are cluttered with dealer info, loan offers, and insurance pitches — irrelevant for a P2P marketplace.",
      solution: "Minimal detail screen showing photo gallery, key specs (year, fuel, KMs, transmission), seller contact info, and a Chat button. No financing, no dealer registration, no EMI.",
      metrics: "Minimal UI | Direct chat | No distractions",
    },
    {
      id: "sell", number: "03", icon: <TrendingUp size={14} />, label: "Sell Car", title: "2-Step Listing",
      tagline: "List your car in 2 minutes",
      problem: "Complex multi-step wizards with 20+ fields discourage individual sellers from listing their cars.",
      solution: "A streamlined 2-step form: Step 1 — upload photos, enter brand/model/year/price. Step 2 — add description and contact info. Hit publish and your car is live. Progressive validation catches errors early.",
      metrics: "2 steps | 6 fields | Instant publish",
    },
    {
      id: "chat", number: "04", icon: <MessageCircle size={14} />, label: "Direct Chat", title: "Buyer-Seller Messaging",
      tagline: "No middlemen, just conversations",
      problem: "Enquiry forms create asynchronous communication. Buyers want to ask questions and negotiate directly without waiting for email responses.",
      solution: "In-app chat powered by Stream Chat. Buyers tap Chat on a listing to open a direct conversation with the seller. Push notifications ensure fast responses. Simple, direct, no intermediaries.",
      metrics: "Stream Chat | Push notifications | Direct messaging",
    },
    {
      id: "profile", number: "05", icon: <Users size={14} />, label: "User Profile", title: "Seller & Buyer Profiles",
      tagline: "Trust through transparency",
      problem: "On P2P marketplaces, trust is the biggest barrier. Buyers need to know the seller is real before committing to a purchase.",
      solution: "User profiles show listing history, join date, phone verification status, and response rate. Verified phone badge builds trust. Profile photos and optional bio humanize the interaction.",
      metrics: "Trust indicators | Verified badge | Response rate",
    },
    {
      id: "manage", number: "06", icon: <Home size={14} />, label: "My Listings", title: "Manage Your Cars",
      tagline: "Edit, mark sold, or remove listings",
      problem: "Sellers need to manage their active listings — mark cars as sold, update prices, or remove outdated posts without contacting support.",
      solution: "A My Listings dashboard showing all active and sold cars. Swipe to edit, mark as sold, or delete. Sold cars move to a history tab for reference.",
      metrics: "Active/Sold tabs | Swipe actions | Instant updates",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 24, suffix: "", label: "Screens", sublabel: "Simplified navigation", color: "text-accent" },
    { icon: <GitBranch size={16} />, value: 18, suffix: "", label: "Components", sublabel: "Minimal design system", color: "text-emerald-400" },
    { icon: <Database size={16} />, value: 15, suffix: "+", label: "API Endpoints", sublabel: "Lightweight Laravel API", color: "text-accent" },
    { icon: <Users size={16} />, value: 1, suffix: "", label: "User Type", sublabel: "P2P only", color: "text-cyan-400" },
    { icon: <MessageCircle size={16} />, value: 1, suffix: "", label: "Chat Service", sublabel: "Stream Chat", color: "text-emerald-400" },
    { icon: <Zap size={16} />, value: 1, suffix: "", label: "Push Service", sublabel: "FCM notifications", color: "text-accent" },
  ],
  timelineTitle: "4 phases across 3 months",
  timeline: [
    { phase: "1", title: "Research & Scoping", desc: "P2P marketplace analysis, feature scoping (what NOT to build), user flow design" },
    { phase: "2", title: "Core App Build", desc: "Auth, listings grid, car detail, sell flow, photo upload with camera/gallery" },
    { phase: "3", title: "Chat & Trust", desc: "Stream Chat integration, push notifications, user profiles with verification badges, spam detection" },
    { phase: "4", title: "Polish & Launch", desc: "Android testing on 10+ devices, listing moderation tools, Play Store release" },
  ],
  decisions: [
    {
      title: "Stream Chat over WhatsApp integration",
      icon: <MessageCircle size={16} />,
      alternatives: "WhatsApp Business API, SMS-based contact sharing",
      tradeoff: "Stream Chat requires users to stay in-app. WhatsApp integration would let users chat in their preferred app but adds complexity and cost.",
      decision: "Stream Chat keeps the transaction inside the app. Push notifications ensure fast responses. WhatsApp number is displayed on profiles as a fallback contact option.",
      impact: "Controlled messaging environment. In-app chat history. Push notification delivery. WhatsApp as fallback contact.",
    },
    {
      title: "Minimal 2-step wizard over multi-step forms",
      icon: <TrendingUp size={16} />,
      alternatives: "5+ step wizard with progressive validation, web-based listing form",
      tradeoff: "Fewer steps means less data collected per listing, potentially lower quality listings. But more steps = higher drop-off.",
      decision: "2-step form with only essential fields: photos, brand, model, year, price, description, contact info. Optional fields deferred to edit flow.",
      impact: "Under 2 minutes to list a car. Higher listing completion rate. Lower-quality listings handled by moderation.",
    },
    {
      title: "No dealer registrations, no financing",
      icon: <Home size={16} />,
      alternatives: "Include dealer accounts, loan applications, insurance",
      tradeoff: "Excluding dealers means smaller inventory. Excluding financing means buyers need their own payment arrangement.",
      decision: "Pure P2P with no dealer accounts, no loan applications, no insurance forms. Every feature either directly serves the listing → chat → sale flow or it doesn't exist.",
      impact: "Focused product. Clear value proposition. Zero feature bloat.",
    },
  ],
  challenges: [
    {
      icon: <Shield size={16} />, label: "Spam & Fake Listings",
      problem: "P2P marketplaces attract spam listings — fake cars, duplicate posts, scam prices. Without dealer verification, anyone can post anything.",
      solution: "Phone verification required before first listing. Rate limiting (max 3 listings per day per user). Automated keyword-based flagging for suspicious content. Manual review queue for first-time sellers.",
      result: "95%+ legitimate listings after first week. Spam removed within 1 hour of flagging.",
      metrics: ["Phone verification", "Rate limiting", "Auto-flagging"],
    },
    {
      icon: <Users size={16} />, label: "Building Trust Without Dealers",
      problem: "On dealer-mediated platforms, the dealer is the trusted intermediary. On a P2P app, buyers and sellers are strangers. Trust must be built through the app itself.",
      solution: "Verified phone badge, listing history (how many cars sold previously), response time metric, and optional identity verification. Chat history preserved so disputes can be reviewed.",
      result: "Trust indicators increased chat initiation by 40% and completed sales by 25%.",
      metrics: ["Verified badge", "Listing history", "Response metric"],
    },
    {
      icon: <Database size={16} />, label: "Image Quality & Consistency",
      problem: "Seller-uploaded photos vary wildly in quality — dark garages, cluttered backgrounds, extreme close-ups. Inconsistent images reduce buyer confidence.",
      solution: "In-app camera guide overlay showing ideal framing. Minimum 3 photos required. Auto-enhancement (brightness, contrast) on upload. Blurry photo detection with rejection prompt.",
      result: "70%+ listings meet quality guidelines. Reduced manual moderation by 60%.",
      metrics: ["3 photo minimum", "Auto-enhancement", "Blur detection"],
    },
  ],
  techStackTitle: "The tools and frameworks powering CarzChoice Old App",
  techStack: [
    { name: "React Native (Expo)", cat: "Mobile", desc: "Cross-platform Android app with focused navigation and 18 lightweight components." },
    { name: "Laravel PHP", cat: "Backend", desc: "Minimal REST API with 15+ endpoints for listings, auth, chat, and user profiles." },
    { name: "Stream Chat", cat: "Real-Time", desc: "Direct buyer-seller messaging with push notifications and in-app chat history." },
    { name: "MySQL", cat: "Database", desc: "Simple relational schema for users, listings, and messages — no complex joins needed." },
    { name: "Firebase Cloud Messaging", cat: "Infrastructure", desc: "Push notifications for new chat messages and listing activity alerts." },
    { name: "NativeWind", cat: "UI", desc: "Tailwind CSS utility classes for consistent, fast UI development." },
  ],
  resultsTitle: "Measurable impact from architectural decisions",
  results: [
    { icon: <Smartphone size={20} />, metric: "24", label: "App Screens", desc: "Every screen justified against the core P2P listing → chat → sale flow. Nothing extra." },
    { icon: <GitBranch size={20} />, metric: "18", label: "Reusable Components", desc: "Minimal but complete design system — just enough to build every screen." },
    { icon: <Database size={20} />, metric: "15+", label: "API Endpoints", desc: "Deliberately simple backend. No complex endpoints for financing, dealer management, or bidding." },
    { icon: <MessageCircle size={20} />, metric: "Stream Chat", label: "Direct Messaging", desc: "Push notifications ensure buyers and sellers connect fast without staying in the app." },
    { icon: <Users size={20} />, metric: "P2P Only", label: "No Intermediaries", desc: "Zero dealer accounts. Zero financing. Zero insurance. Just people selling cars to people." },
    { icon: <Zap size={20} />, metric: "3 Months", label: "Time to Ship", desc: "Focused scope meant faster delivery. Every unnecessary feature was a 'no'." },
  ],
  lessons: [
    { title: "A clear 'no' is better than a maybe", what: "Every proposed feature was evaluated against one question: does this help someone sell or buy a used car? If not, it was rejected.", why: "Feature creep is the biggest risk for P2P marketplaces. Dealer registrations, financing, bidding — all valuable features that would dilute the core P2P experience.", impact: "Shipped in 3 months. Minimal maintenance burden. Users understand the app immediately." },
    { title: "Trust is the product on P2P platforms", what: "Invest in trust indicators (verified phone, listing history, response rate) before adding any new feature.", why: "Without trust, buyers won't contact sellers. Without trust, sellers won't list. Everything else is secondary.", impact: "Trust indicators were the highest-impact feature per line of code." },
    { title: "Moderation is not optional", what: "Build automated moderation (keyword flagging, rate limiting, blur detection) from day one, not as an afterthought.", why: "P2P platforms attract spam immediately. Manual moderation doesn't scale. By the time you notice a spam problem, user trust is already damaged.", impact: "Automated moderation caught 90%+ of spam before any user saw it." },
  ],
  cta: {
    href: "/projects/car-choice",
    icon: <Car size={24} />,
    title: "Carz Choice",
    subtitle: "Used Car Marketplace",
    description: "The full-featured car marketplace with dealer registration, real-time chat, financing, and multi-attribute search — built for the Indian market.",
  },
};
