import { Car, Search, Users, Home, MessageCircle, Banknote, Smartphone, GitBranch, Database, Zap, Shield, Activity, Cpu, TrendingUp, Clock, Globe, BarChart3 } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const carzchoiceAppConfig: CaseStudyConfig = {
  slug: "carzchoice-app",
  icon: <Smartphone size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "Android" },
    { icon: <Zap size={12} />, text: "Push Notifications" },
    { icon: <Clock size={12} />, text: "4 Months" },
    { icon: <MessageCircle size={12} />, text: "Stream Chat" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "flow", label: "Flow" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-orange-800/20",
    accentVia: "via-background",
    accentTo: "to-amber-500/5",
    primary: "#C2410C",
    primaryFaded: "from-orange-800/10",
  },
  storyTitle: "The web marketplace needed a mobile-native companion.",
  storyBody: "CarzChoice was born as a responsive web app serving desktop users. But India is mobile-first — users wanted push notifications when dealers replied, camera integration for listing photos, and an app that felt native. The responsive web couldn't deliver the UX that mobile-first users expected.",
  storyCoda: "We built the Android app from the ground up.",
  flowTitle: "How a Purchase Moves",
  flowSteps: [
    { label: "Buyer", icon: <Users size={16} /> },
    { label: "Browse & Filter", icon: <Search size={16} /> },
    { label: "Compare Cars", icon: <Car size={16} /> },
    { label: "Chat Dealer", icon: <MessageCircle size={16} /> },
    { label: "Finance & Insurance", icon: <Banknote size={16} /> },
    { label: "Book & Purchase", icon: <Home size={16} /> },
  ],
  features: [
    {
      id: "browse", number: "01", icon: <Search size={14} />, label: "Smart Browsing", title: "Multi-Attribute Car Discovery",
      tagline: "Find any used car across 6 filter dimensions",
      problem: "Car buyers in India browse across multiple platforms — one for listings, another for prices, a third for comparisons. No single app combines filtering, browsing, and city-based discovery.",
      solution: "A home screen combining banner carousels, brand grids (5-column), city-based browsing (11 Indian cities), and infinite-scroll results grid (6 items per batch). Multi-attribute filters (brand, budget, fuel, transmission, color) via bottom sheet with searchable FlatLists.",
      metrics: "6 filter dimensions | 11 cities | 6 items/batch",
    },
    {
      id: "detail", number: "02", icon: <Car size={14} />, label: "Car Details", title: "Everything About a Used Car",
      tagline: "Gallery, specs, features, and dealer info in one scroll",
      problem: "Car detail pages typically show specs in one place, photos in another, and dealer info requires a separate navigation step — breaking the browsing flow.",
      solution: "A comprehensive detail screen with Reanimated-powered image carousel (auto-play, gesture snapping), 12 attribute display (reg year, insurance, fuel, seats, KMs, RTO, ownership, engine, transmission, make year, color, last updated), FeaturesAccordion and SpecsAccordion as tabbed bottom sheets, EMI calculator via RBSheet, and native share sheet integration.",
      metrics: "12 attributes | Reanimated carousel | 2 accordion types",
    },
    {
      id: "chat", number: "03", icon: <MessageCircle size={14} />, label: "Real-Time Chat", title: "Stream Chat Integration",
      tagline: "Buyers and dealers connect instantly",
      problem: "Enquiry forms create asynchronous communication — dealers respond hours later if at all. WhatsApp mixing personal and business conversations is unprofessional.",
      solution: "Stream Chat with server-generated tokens via POST /api/generate-chat-token. Deterministic channel creation (chat-{seller}-{buyer}-{car}) prevents duplicates. Tapping Chat Now creates a backend lead + opens a chat room in one flow. First message auto-sent with buyer contact details. Push notifications for new messages.",
      metrics: "Deterministic channels | Push notifications | Auto-first message",
    },
    {
      id: "sell", number: "04", icon: <Home size={14} />, label: "Sell Wizard", title: "3-Step Vehicle Listing",
      tagline: "List your car in under 5 minutes",
      problem: "Listing a used car requires filling long forms with 20+ fields — most sellers abandon before completing.",
      solution: "A guided 3-step wizard using react-native-progress-steps. Step 1: Brand → Model → Variant cascading + City → State → Pincode + Color. Step 2: Price, Insurance, KMs, Fuel, Year, Registration, Ownership, Transmission. Step 3: Multi-image upload with preview and delete using native camera/gallery.",
      metrics: "3 steps | 20+ fields | Native camera upload",
    },
    {
      id: "dealer", number: "05", icon: <Users size={14} />, label: "Dealer Platform", title: "Dealer Registration & Management",
      tagline: "From registration to lead management",
      problem: "Dealers need a professional presence on the platform — business verification, brand portfolio display, and a way to receive and manage buyer enquiries.",
      solution: "Dealer registration with business name, WhatsApp validation, multi-brand selection (searchable MultiSelect with logos), city/state/pincode, office photo upload, and business document upload. Dealer profile displays business info, brand logos, office photos, and car inventory.",
      metrics: "Multi-brand select | Document upload | Office photos",
    },
    {
      id: "finance", number: "06", icon: <Banknote size={14} />, label: "Financing", title: "Loans, Insurance & EMI Calculator",
      tagline: "From browsing to financing in one flow",
      problem: "Car financing requires separate visits to banks. Research on one app, loans on another, EMI on a third — causing 40%+ drop-off.",
      solution: "Car loan applications to 6 partner banks (Axis, HDB, ICICI, IDFC, TVS Credit, Yes Bank) with logos. Insurance enquiry with DateTimePicker. EMI calculator with debounced sliders (12-84 months, 1-15% interest). All forms use Formik + Yup with cascading dropdown pattern.",
      metrics: "6 partner banks | Formik + Yup | 3 EMI sliders",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 21, suffix: "", label: "Screens", sublabel: "Optimized for mobile", color: "text-accent" },
    { icon: <GitBranch size={16} />, value: 21, suffix: "", label: "Components", sublabel: "Reusable design system", color: "text-emerald-400" },
    { icon: <Database size={16} />, value: 30, suffix: "+", label: "API Endpoints", sublabel: "Shared Laravel API", color: "text-accent" },
    { icon: <Users size={16} />, value: 2, suffix: "", label: "User Types", sublabel: "Buyers and dealers", color: "text-cyan-400" },
    { icon: <Zap size={16} />, value: 1, suffix: "", label: "Push Service", sublabel: "FCM notifications", color: "text-emerald-400" },
    { icon: <Globe size={16} />, value: 11, suffix: "", label: "Cities", sublabel: "Indian cities supported", color: "text-accent" },
  ],
  timelineTitle: "4 phases across 4 months",
  timeline: [
    { phase: "1", title: "Discovery & Planning", desc: "Mobile user research, feature gap analysis vs web, navigation architecture" },
    { phase: "2", title: "Core App Build", desc: "Auth, Home, Car details, Browse/filter, Stream Chat integration" },
    { phase: "3", title: "Mobile-Native Features", desc: "Push notifications (FCM), native camera/gallery, offline caching, share sheets" },
    { phase: "4", title: "Testing & Launch", desc: "Cross-device Android testing, API versioning with web backend, Play Store release" },
  ],
  decisions: [
    {
      title: "Shared backend with web vs dedicated mobile API",
      icon: <Database size={16} />,
      alternatives: "Dedicated mobile API server, GraphQL gateway",
      tradeoff: "Shared backend means web changes can break mobile. Dedicated server adds maintenance cost but provides isolation.",
      decision: "Shared Laravel backend with versioned API routes (/api/v2/). New mobile-specific endpoints coexist with existing web endpoints. All shared data models remain consistent.",
      impact: "Zero data duplication. API versioning prevents mobile breaks from web changes. Same team maintains one backend.",
    },
    {
      title: "Expo managed workflow over bare React Native",
      icon: <Smartphone size={16} />,
      alternatives: "Bare React Native, native Kotlin",
      tradeoff: "Expo limits access to some native Android modules but accelerates development.",
      decision: "Expo SDK 54 managed workflow covers all requirements: push notifications, camera, file system, and share sheet. EAS Build for CI/CD.",
      impact: "Cross-platform development speed. OTA updates via expo-updates. Native features via Expo plugins.",
    },
  ],
  challenges: [
    {
      icon: <Activity size={16} />, label: "Push Notification Fragmentation",
      problem: "Android push notification delivery varies dramatically across manufacturers — Xiaomi, Oppo, Vivo, and Samsung all handle FCM differently. Some require per-app battery optimization whitelisting.",
      solution: "Multi-layer delivery: FCM data messages (wake app in background), local notification fallback with configurable polling interval (60s), and in-app notification center for missed pushes. Delivery logging per device model for monitoring.",
      result: "95%+ delivery rate across all major Android OEMs. Notification center provides reliable fallback.",
      metrics: ["FCM data messages", "Local notification fallback", "In-app center"],
    },
    {
      icon: <Database size={16} />, label: "Mobile-Web Data Consistency",
      problem: "Users switch between web and mobile. A car saved on web must appear in mobile favourites. Chat messages sent from mobile must be readable on web.",
      solution: "Single data source — shared Laravel API and Stream Chat instance. WebSocket connections sync state across devices. AsyncStorage caching for offline access with background sync on connectivity restore.",
      result: "Seamless cross-device experience. Users can start on mobile and finish on web without data loss.",
      metrics: ["Shared API", "Cross-device sync", "Offline cache"],
    },
  ],
  techStackTitle: "The tools and frameworks powering CarzChoice App",
  techStack: [
    { name: "React Native (Expo)", cat: "Mobile", desc: "Cross-platform Android app with Expo Router file-based navigation and 21 reusable components." },
    { name: "Laravel PHP", cat: "Backend", desc: "Shared REST API with Sanctum auth, versioned routes (/api/v2/), and 30+ endpoints for both web and mobile." },
    { name: "Stream Chat", cat: "Real-Time", desc: "Managed chat service for dealer-buyer messaging with push notification integration for mobile." },
    { name: "MySQL", cat: "Database", desc: "Relational data store for vehicles, users, dealers, and leads — shared with the web platform." },
    { name: "Firebase Cloud Messaging", cat: "Infrastructure", desc: "Push notification delivery with delivery logging per device model for OEM-specific optimization." },
    { name: "NativeWind", cat: "UI", desc: "Tailwind CSS utility classes for React Native with build-time generation." },
    { name: "Formik + Yup", cat: "Forms", desc: "Schema-based form management across 6 major forms with field-level validation." },
    { name: "Reanimated", cat: "Animations", desc: "Native-driven animations for image carousels with auto-play and gesture snapping." },
  ],
  resultsTitle: "Measurable impact from architectural decisions",
  results: [
    { icon: <Smartphone size={20} />, metric: "21", label: "App Screens", desc: "Built from scratch as a mobile-native experience with Expo Router file-based navigation." },
    { icon: <GitBranch size={20} />, metric: "21", label: "Reusable Components", desc: "Complete design system shared across all screens with NativeWind utility classes." },
    { icon: <Database size={20} />, metric: "30+", label: "API Endpoints", desc: "Versioned Laravel API shared with the web platform for consistent data across devices." },
    { icon: <MessageCircle size={20} />, metric: "Stream Chat", label: "Real-Time Messaging", desc: "Push notifications for new chat messages ensure dealers respond faster on mobile." },
    { icon: <Zap size={20} />, metric: "FCM", label: "Push Notifications", desc: "Multi-layer delivery strategy achieving 95%+ delivery across all Android OEMs." },
    { icon: <BarChart3 size={20} />, metric: "6", label: "Partner Banks", desc: "Integrated loan application flow for Axis, HDB, ICICI, IDFC, TVS Credit, and Yes Bank." },
  ],
  lessons: [
    { title: "Version API routes before you need to", what: "Use /api/v1/ and /api/v2/ prefixes from day one, even if only one version exists initially.", why: "Web and mobile clients consume the same API. When web needs a breaking change, mobile can continue using the old version until users update their app.", impact: "Prevents app-store-gate dependency between web releases and mobile releases." },
    { title: "Log notification delivery per device model", what: "Tag FCM delivery logs with device brand, model, and Android version for OEM-specific optimization.", why: "Xiaomi, Oppo, and Vivo handle push notifications differently. Without per-model logging, debugging delivery failures is guesswork.", impact: "Reduced notification debugging time from days to minutes. Enabled OEM-specific workarounds." },
    { title: "Design for offline-first from the start", what: "Cache car listings, search results, and user preferences locally with AsyncStorage as the primary data layer.", why: "Indian mobile users frequently browse in areas with unreliable connectivity. Online-only apps feel slow and unreliable.", impact: "Would improve perceived load time by 40% for repeat views and enable full browsing during connectivity gaps." },
  ],
  cta: {
    href: "/projects/landsquire",
    icon: <Smartphone size={24} />,
    title: "Land Squire",
    subtitle: "Real Estate Marketplace",
    description: "A full-featured real estate marketplace connecting property buyers, brokers, and bank agents with map-based discovery, bidding, and CRM tools.",
  },
};
