import { Home, Map, Users, Building2, Banknote, Globe, BarChart3, Smartphone, GitBranch, Database, Zap, Shield, Activity, Cpu, TrendingUp, Clock, Search } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const landSquireConfig: CaseStudyConfig = {
  slug: "landsquire",
  icon: <Home size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "iOS + Android" },
    { icon: <Users size={12} />, text: "3 User Roles" },
    { icon: <Clock size={12} />, text: "6 Months" },
    { icon: <Map size={12} />, text: "React Native + Laravel" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "flow", label: "Flow" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-emerald-900/20",
    accentVia: "via-background",
    accentTo: "to-green-500/5",
    primary: "#1B4332",
    primaryFaded: "from-emerald-900/10",
  },
  storyTitle: "Real estate in India is fragmented.",
  storyBody: "Buyers jump between listing sites, brokers manage leads in spreadsheets, and bank agents struggle to find loan customers. There was no single, unified mobile experience connecting all three parties with map-based discovery, real-time bidding, and CRM tools.",
  storyCoda: "We built the missing layer.",
  flowTitle: "How a Deal Moves",
  flowSteps: [
    { label: "Buyer", icon: <Users size={16} /> },
    { label: "Find Property on Map", icon: <Map size={16} /> },
    { label: "Compare & Shortlist", icon: <Search size={16} /> },
    { label: "Place Bid", icon: <Banknote size={16} /> },
    { label: "Broker Negotiation", icon: <Users size={16} /> },
    { label: "Deal Closed", icon: <Home size={16} /> },
  ],
  features: [
    {
      id: "map", number: "01", icon: <Map size={14} />, label: "Map Discovery", title: "Map-Based Property Discovery",
      tagline: "Find properties where they actually are — on a map",
      problem: "List-based browsing hides geographic context. Users couldn't see where properties are relative to each other or understand neighborhood density at a glance.",
      solution: "Properties render directly on an interactive Google Map as custom price tag markers. A custom useMapData hook (30+ state variables) manages viewport tracking, visibility culling, and filter controls. Viewport culling with a 50% buffer zone prevents rendering thousands of markers simultaneously. Project boundaries display as green polygon overlays with locally cached aerial plan images.",
      metrics: "30+ hook state vars | 50% culling buffer | Custom markers",
    },
    {
      id: "roles", number: "02", icon: <Users size={14} />, label: "Role-Based", title: "Three Roles, One Codebase",
      tagline: "One app, three perspectives",
      problem: "Building separate apps for buyers, brokers, and bank agents would triple development and maintenance costs.",
      solution: "A single user_type field in the auth response determines post-login navigation, available features, and dashboard content. The signup form dynamically renders role-specific fields. Buyers see map-first discovery, brokers get a CRM dashboard, bank agents receive loan enquiries — all from one codebase.",
      metrics: "3 user types | Dynamic forms | Role-aware routing",
    },
    {
      id: "listing", number: "03", icon: <Home size={14} />, label: "Property Listing", title: "Multi-Step Property Listing",
      tagline: "Listing a property shouldn't take a week",
      problem: "Complex property listing forms overwhelm users with too many fields at once, causing high abandonment rates.",
      solution: "Guided 4-step (sell) and 3-step (rent) wizards with react-native-progress-steps. Each step validates progressively — errors reported immediately. Google Places Autocomplete with session tokens for accurate address resolution. Media uploads support images, videos, PDFs, and master plans with MIME type validation.",
      metrics: "4-step sell | 3-step rent | Progressive validation",
    },
    {
      id: "bidding", number: "04", icon: <Banknote size={14} />, label: "Bidding", title: "Competitive Bidding System",
      tagline: "Buyers compete, sellers win",
      problem: "Fixed-price listings don't capture market demand. Sellers miss out on competitive offers while buyers can't express higher willingness to pay.",
      solution: "Properties support competitive bidding with intelligent validation — minimum bids at 50% of asking price to prevent lowball offers. Brokers toggle bidding on/off and set end dates. Reuses existing sendenquiry API with a bidamount field, keeping architecture simple.",
      metrics: "50% minimum bid | Toggle control | End date config",
    },
    {
      id: "crm", number: "05", icon: <BarChart3 size={14} />, label: "CRM", title: "Full CRM for Brokers",
      tagline: "Every lead, every follow-up, in one place",
      problem: "Brokers managed leads across disconnected channels — phone, WhatsApp, walk-ins — with no centralized tracking or follow-up system.",
      solution: "Full lead management system with advanced filters (city, date range, property type, status), follow-up timeline with notes, and direct call/WhatsApp integration via deep linking. Status tracking (new, qualified, won, not responded, final) with audit trail for complete pipeline visibility.",
      metrics: "5 lead statuses | Notes timeline | Call/WhatsApp actions",
    },
    {
      id: "i18n", number: "06", icon: <Globe size={14} />, label: "i18n", title: "Multi-Language Support",
      tagline: "Speak your language",
      problem: "English-only apps exclude the majority of Indian real estate buyers who prefer Hindi, especially in Tier 2 and Tier 3 cities.",
      solution: "Full English and Hindi localization with 130+ translation keys via i18next. Conditional font selection — Rubik for English, NotoSerifDevanagari for Hindi — with 12 bundled font files (6 weights x 2 languages). Language preference persists in AsyncStorage.",
      metrics: "130+ keys | 12 font files | Persisted preference",
    },
    {
      id: "projects", number: "07", icon: <Building2 size={14} />, label: "Projects", title: "Upcoming Projects Visualization",
      tagline: "See the future of development, mapped",
      problem: "Upcoming real estate projects lack visual context — buyers can't see project boundaries, proximity to properties, or neighborhood layout.",
      solution: "Development projects render as green polygon boundaries with semi-transparent aerial plan overlays on the map. Polygon coordinates parsed from JSON arrays. Centroid calculation places marker at geometric center. Map images cached locally with expo-file-system. Platform-specific bounds ordering for correct Overlay rendering.",
      metrics: "Polygon overlay | Cached images | Cross-platform bounds",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 25, suffix: "+", label: "Screens", sublabel: "Auth & root groups", color: "text-accent" },
    { icon: <GitBranch size={16} />, value: 35, suffix: "+", label: "Components", sublabel: "Reusable design system", color: "text-emerald-400" },
    { icon: <Database size={16} />, value: 35, suffix: "+", label: "API Endpoints", sublabel: "Laravel REST API", color: "text-accent" },
    { icon: <Users size={16} />, value: 3, suffix: "", label: "User Roles", sublabel: "Buyer, broker, bank agent", color: "text-cyan-400" },
    { icon: <Globe size={16} />, value: 130, suffix: "+", label: "Translations", sublabel: "English + Hindi i18n", color: "text-emerald-400" },
    { icon: <Activity size={16} />, value: 54, suffix: "", label: "Custom Icons", sublabel: "PNG icon design system", color: "text-accent" },
  ],
  timelineTitle: "10 phases across 6 months",
  timeline: [
    { phase: "1", title: "Research & Planning", desc: "Competitive analysis of 10+ real estate apps, architecture design, Expo project scaffolding" },
    { phase: "2", title: "Authentication & Navigation", desc: "OTP auth flow, Expo Router navigation structure, user context, role-based routing" },
    { phase: "3", title: "Design System", desc: "Color palette, typography (12 fonts), 35+ reusable components, icon library" },
    { phase: "4", title: "Map Integration", desc: "Google Maps setup, custom price markers, useMapData hook, viewport culling, project overlays" },
    { phase: "5", title: "Property Features", desc: "Multi-step listing wizards, property detail screen, 15 sub-components, lightbox with pinch-zoom" },
    { phase: "6", title: "Bidding & CRM", desc: "Bidding system with validation, CRM portal with lead management, filters, notes timeline" },
    { phase: "7", title: "Multi-Language & i18n", desc: "i18next setup, 130+ translations (EN + HI), dual font loading, language switching" },
    { phase: "8", title: "Dashboard & Admin", desc: "Loan enquiry management, bank agent profiles, edit/delete property workflows" },
    { phase: "9", title: "Testing & Polish", desc: "Cross-platform testing, map performance optimization, Reanimated animations" },
    { phase: "10", title: "Launch", desc: "EAS Build configuration, app store submission, expo-updates setup, monitoring" },
  ],
  decisions: [
    {
      title: "Expo managed over bare React Native",
      icon: <Smartphone size={16} />,
      alternatives: "Bare React Native, Native Swift/Kotlin",
      tradeoff: "Expo limits access to some native modules, but all required functionality was available in SDK 54.",
      decision: "SDK 54 covers maps, fonts, file system, image picker, video, and notifications via Expo plugins. EAS Update enables OTA bug fixes without app store review.",
      impact: "Cross-platform from day one. Over-the-air updates. No eject needed despite complex map and media features.",
    },
    {
      title: "Custom useMapData hook over Redux",
      icon: <Cpu size={16} />,
      alternatives: "Redux Toolkit, Zustand, useReducer",
      tradeoff: "30+ state variables in one hook creates complexity. The hook does significant derivation (viewport culling, coordinate transforms).",
      decision: "Centralizing all map state in a custom hook keeps the screen component clean while providing all derivation logic in one testable unit. The hook returns derived values so the screen doesn't need to recompute.",
      impact: "Zero state management dependencies. Clean separation of map logic from UI. Easy to reason about despite complexity.",
    },
    {
      title: "Laravel PHP over Node.js",
      icon: <Database size={16} />,
      alternatives: "Node.js + Express, Python + Django",
      tradeoff: "PHP has higher server cost per request. Laravel's ORM is less performant than raw queries for complex joins.",
      decision: "Laravel provides built-in Sanctum token auth, Validator with field-level errors, and Cache facade — reducing dependency count by 5+ packages. Consistent patterns across 35+ endpoints.",
      impact: "35+ endpoints built with consistent auth, validation, and caching. Sanctum handles token management out of the box.",
    },
    {
      title: "i18next with dual fonts over simple strings",
      icon: <Globe size={16} />,
      alternatives: "Simple JSON key-value, single font, separate apps per language",
      tradeoff: "12 bundled font files (6 weights x 2 typefaces) increase app bundle size by ~3MB. Conditional fontFamily logic adds complexity.",
      decision: "i18next provides interpolation, pluralization, and language change callbacks. Font switching through conditional fontFamily based on i18n.language. Both fonts preloaded via expo-font.",
      impact: "Instant language switching. Correct script rendering for Devanagari. Hindi support doubles addressable market in North India.",
    },
  ],
  challenges: [
    {
      icon: <Map size={16} />, label: "Map Performance at Scale",
      problem: "Rendering hundreds of property markers simultaneously caused jank. Each custom price tag marker needed position tracking, tap response, and visual polish.",
      solution: "Three-layer optimization: viewport culling with 50% buffer zone renders only visible markers, tracksViewChanges disabled after 100ms on custom markers, React.memo on PriceMarker and MarkersRenderer.",
      result: "Smooth panning with large property sets. Custom markers with optimized viewport culling.",
      metrics: ["60fps target", "50% buffer", "100ms optimization"],
    },
    {
      icon: <Shield size={16} />, label: "API Key Security",
      problem: "Hardcoded Google Maps API keys in mobile bundles are vulnerable to extraction and unauthorized use.",
      solution: "Server-side key delivery with 24-hour local caching. Three-level fallback: server key, app.json fallback, empty string. Key refresh on login. Silent fallback on fetch failure.",
      result: "Key rotation without app store updates. Zero unauthorized key usage incidents.",
      metrics: ["24h cache", "3-level fallback", "Silent recovery"],
    },
    {
      icon: <Building2 size={16} />, label: "Cross-Platform Map Overlays",
      problem: "Project polygon boundaries rendered differently on Android vs iOS due to platform-specific coordinate handling in Overlay component.",
      solution: "Platform-specific bounds construction. Polygon coordinates parsed from JSON strings. Centroid calculation for marker placement. File system caching with MD5 checksum for plan images.",
      result: "Consistent overlay rendering across both platforms. Optimized image loading with local caching.",
      metrics: ["2 platforms", "Cached images", "Centroid calc"],
    },
    {
      icon: <Database size={16} />, label: "Inconsistent API Parsing",
      problem: "Gallery images, videos, amenities, and price history returned in inconsistent formats — arrays, objects, or JSON strings with no predictable pattern.",
      solution: "Each data field has its own robust parsing function with type detection, try-catch blocks, and defensive defaults. Handles arrays, objects, strings, and nulls per field type.",
      result: "Zero crashes from malformed API data across all 15 PropertyDetails sub-components.",
      metrics: ["15 components", "Zero parse crashes", "Defensive defaults"],
    },
  ],
  techStackTitle: "The tools and frameworks powering Land Squire",
  techStack: [
    { name: "React Native (Expo)", cat: "Mobile", desc: "Cross-platform iOS/Android/Web with Expo Router file-based navigation and 35+ reusable components forming a complete design system." },
    { name: "Laravel PHP", cat: "Backend", desc: "REST API with Sanctum auth, Validator for field-level errors, and Cache facade for server-side response caching across 35+ endpoints." },
    { name: "Google Maps", cat: "Maps", desc: "Interactive map rendering with custom price markers, polygon project overlays, geocoding, and Places Autocomplete for address resolution." },
    { name: "NativeWind", cat: "UI", desc: "Tailwind CSS utility classes for React Native. Build-time generation via Babel plugin eliminates runtime CSS-in-JS overhead." },
    { name: "MySQL", cat: "Database", desc: "Relational data store for properties, users, enquiries, CRM leads, and loan applications with JSON columns for flexible amenity/media data." },
    { name: "i18next", cat: "i18n", desc: "Internationalization framework with 130+ keys per language. Dual font: Rubik (English) and NotoSerifDevanagari (Hindi)." },
    { name: "Reanimated", cat: "Animations", desc: "Native-driven animations for tab bar spring effects, lightbox pinch-to-zoom, and smooth card transitions at 60fps." },
    { name: "React Context", cat: "State", desc: "UserContext provides auth state and map API keys to all screens. Custom useMapData hook manages 30+ map state variables." },
  ],
  resultsTitle: "Measurable impact from architectural decisions",
  results: [
    { icon: <Map size={20} />, metric: "25+", label: "App Screens", desc: "Organized into 2 nav groups (auth, root) with Expo Router file-based routing across tabs and stacked screens." },
    { icon: <GitBranch size={20} />, metric: "35+", label: "Reusable Components", desc: "Complete design system: 15 PropertyDetails sub-components, 4 map components, 5 form screens, 16 general components." },
    { icon: <Database size={20} />, metric: "35+", label: "API Endpoints", desc: "Laravel REST API with Sanctum auth, field-level validation, and server-side caching across endpoints." },
    { icon: <Users size={20} />, metric: "3", label: "User Roles", desc: "Buyers, brokers, and bank agents from one codebase. Role-aware navigation and dynamic form rendering." },
    { icon: <Globe size={20} />, metric: "130+", label: "i18n Translations", desc: "Full English and Hindi localization with 12 bundled font files for correct script rendering." },
    { icon: <Clock size={20} />, metric: "6 mo.", label: "Time to Ship", desc: "From research to app store launch across 10 phases spanning design, build, test, and deploy." },
  ],
  lessons: [
    { title: "Split useMapData into smaller, focused hooks", what: "Extract smaller hooks: useMapFilter (filter state), useMapRegion (viewport + bounds), useMapMarkers (marker visibility + rendering) instead of one hook managing 30+ variables.", why: "The current hook has grown beyond what a single unit should manage. Derivation logic for viewport culling and centroid calculation is mixed with state management. Smaller hooks would be independently testable.", impact: "Would reduce the hook from 533 lines to 3 hooks of ~180 lines each. Single responsibility and clear test boundaries." },
    { title: "Add offline-first architecture from the start", what: "Local SQLite cache for recently viewed properties, cached search results, and pending enquiries that sync when connectivity returns.", why: "Real estate browsing often happens on the go with unreliable connectivity. Currently the app requires connectivity for every API call.", impact: "Would improve perceived load time by 60% for repeat views and enable full offline browsing of cached data." },
    { title: "Abstract JSON parsing into an Axios interceptor", what: "Build an Axios response interceptor that normalizes all inconsistent API responses before they reach any component.", why: "The safe-parse utility is copied across multiple components. A single interceptor would handle all inconsistent data (gallery, videos, amenities) in one place.", impact: "Would eliminate ~200 lines of duplicated parsing logic across 15+ components." },
  ],
  cta: {
    href: "/projects/car-choice",
    icon: <Smartphone size={24} />,
    title: "Carz Choice",
    subtitle: "Used Car Marketplace",
    description: "A full-featured used car marketplace connecting buyers and dealers with real-time chat, multi-attribute search, financing, and a sell wizard.",
  },
};
