import { Cpu, Smartphone, Layout, Clock, Image, Swords, BarChart3, GitBranch, Database, Users, Search, Activity, MessageCircle } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const victoryVisionConfig: CaseStudyConfig = {
  slug: "victory-vision",
  icon: <Cpu size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "iOS + Android" },
    { icon: <Cpu size={12} />, text: "Expo SDK 53" },
    { icon: <Clock size={12} />, text: "4.5 Months" },
    { icon: <Layout size={12} />, text: "10 Screens" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "flow", label: "Flow" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-[#111F54]/20",
    accentVia: "via-background",
    accentTo: "to-blue-500/5",
    primary: "#111F54",
    primaryFaded: "from-[#111F54]/10",
  },
  storyTitle: "Millions play fantasy sports daily. Most rely on gut feeling.",
  storyBody: "Fantasy cricket players manually track player form across multiple websites, compare stats, and guess at captain choices. 10+ minutes of research for every contest entry — with no objective way to evaluate their team before submitting.",
  storyCoda: "Victory Vision replaces hours of manual work with seconds of AI intelligence.",
  flowTitle: "How Data Moves",
  flowSteps: [
    { label: "User", icon: <Smartphone size={16} /> },
    { label: "Mobile App (Expo SDK 53)", icon: <Smartphone size={16} /> },
    { label: "REST API (api.victoryvision.live)", icon: <Database size={16} /> },
    { label: "AI Engine", icon: <Cpu size={16} /> },
    { label: "Analysis Result", icon: <BarChart3 size={16} /> },
    { label: "Push Notification", icon: <MessageCircle size={16} /> },
    { label: "User", icon: <Smartphone size={16} /> },
  ],
  features: [
    {
      id: "ai-teams", number: "01", icon: <Cpu size={14} />, label: "AI Teams", title: "AI Team Generation Engine",
      tagline: "Safe and risky teams with dynamic green/orange theming",
      problem: "Fantasy players spend 10+ minutes researching player form, comparing stats across websites, and guessing at captain choices — before every contest entry.",
      solution: "Users configure match, contest type, risk level, and auto-pick captain/VC toggles. The AI produces paired safe (green) and risky (orange) teams with role distribution (WK/BAT/AR/BOWL), win rate projections, and one-tap clipboard copy. Teams are grouped by generation minute using ISO date truncation.",
      metrics: "2 zone themes | 4 role types | 30s generation",
    },
    {
      id: "screenshot", number: "02", icon: <Image size={14} />, label: "Screenshot AI", title: "Fantasy Screenshot Analysis",
      tagline: "Upload any Dream11 team and get instant AI feedback",
      problem: "After submitting a fantasy team, users manually calculate points, compare with friends, and have no way to get objective feedback on their selections.",
      solution: "Users pick a screenshot via expo-document-picker. The image is sent to the server via multipart form upload with userId. AI processes it and returns structured analysis: points breakdown, captain evaluation, improvement suggestions, and strong points in a responsive 2-column grid.",
      metrics: "multipart upload | 2-col grid | 1 component",
    },
    {
      id: "match-hub", number: "03", icon: <Swords size={14} />, label: "Match Hub", title: "Match Intelligence Center",
      tagline: "Predictions, AI teams, and lineups in three swipeable tabs",
      problem: "Users toggle between 3+ apps for match predictions, team recommendations, and playing XI — losing context with every switch.",
      solution: "A nested scroll architecture — parent FlatList with banner, head-to-head, and swipeable TabView for Predictions (toss probability, score, top players), AI Teams (safe + risky), and Lineups (playing XI filterable by role). Nested scroll conflicts resolved via nestedScrollEnabled and scrollEnabled pattern.",
      metrics: "3 swipeable tabs | nested scroll | role filtering",
    },
    {
      id: "dashboard", number: "04", icon: <BarChart3 size={14} />, label: "Dashboard", title: "Performance Reports Dashboard",
      tagline: "Net profit, win rate, top picks, and captain analysis",
      problem: "Fantasy players have no single dashboard showing their performance across contests — they rely on memory and platform standings.",
      solution: "Three dashboard sections: Performance Summary (net profit, win rate, contests played, average rank), Top Player Picks (successful selections with rates), and Captain Analysis (best choices, need-work areas, AI insights). All data from a single API endpoint through GlobalProviderReport context.",
      metrics: "3 sections | 1 API endpoint | pull-to-refresh",
    },
    {
      id: "navigation", number: "05", icon: <Layout size={14} />, label: "Navigation", title: "Custom Animated Tab Bar",
      tagline: "Spring physics, floating indicator, and icon morphing",
      problem: "Default tab bars are static. Users navigate between 4+ sections and need clear, delightful affordances for which section is active.",
      solution: "Fully custom bottom tab bar with React Native Animated API. Each TabItem manages Animated.Value refs for scale (0.84→1.0), translateY (-35px float), label opacity (0→1 over 400ms), and label translateY. Floating indicator driven by animated translateX. Spring physics: friction 6, tension 50.",
      metrics: "spring physics | 4 animated values | 400ms fade",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 10, suffix: "", label: "App Screens", sublabel: "Expo Router file-based", color: "text-accent" },
    { icon: <GitBranch size={16} />, value: 22, suffix: "+", label: "Components", sublabel: "Reusable UI system", color: "text-emerald-400" },
    { icon: <Database size={16} />, value: 15, suffix: "+", label: "API Endpoints", sublabel: "Node.js REST API", color: "text-accent" },
    { icon: <Users size={16} />, value: 2, suffix: "", label: "Nav Groups", sublabel: "Auth + Root tabs", color: "text-cyan-400" },
    { icon: <Cpu size={16} />, value: 2, suffix: "", label: "Theme Zones", sublabel: "Safe / Risky", color: "text-emerald-400" },
    { icon: <Layout size={16} />, value: 11, suffix: "", label: "Custom Icons", sublabel: "Tab bar + features", color: "text-accent" },
  ],
  timelineTitle: "6 phases across 4.5 months",
  timeline: [
    { phase: "1", title: "Discovery & Design", desc: "Fantasy sports market research, competitor analysis, user flow design, navigation tree, design system (navy, space mono, green/orange)" },
    { phase: "2", title: "Auth & Foundation", desc: "OTP authentication flow, Expo Router auth/root groups, GlobalProviderReport context, base component library" },
    { phase: "3", title: "Match Intelligence Hub", desc: "Match listing with today/upcoming tabs, nested scroll + TabView, predictions, lineups with role filtering" },
    { phase: "4", title: "AI Team Engine", desc: "Safe/risky generation, dynamic green/orange theming, temporal pairing by generation minute, clipboard copy" },
    { phase: "5", title: "Analysis & Reporting", desc: "Screenshot upload and AI analysis pipeline, performance dashboard, custom animated tab bar" },
    { phase: "6", title: "Quality & Release", desc: "Cross-device testing (API 24-35), EAS Build profiles, edge case handling, production launch" },
  ],
  decisions: [
    {
      title: "React Context over Redux or Zustand",
      icon: <Database size={16} />,
      alternatives: "Redux Toolkit, Zustand, Jotai",
      tradeoff: "Context re-renders all consumers on any state change. With 3 data sources and 10 screens, this could cause unnecessary re-renders as data grows.",
      decision: "Single GlobalProviderReport context with useState hydration. refreshGlobalData() called after login and on pull-to-refresh provides consistent data freshness. The app has one global data dependency (match listings) plus two supplementary sources — well within Context's sweet spot.",
      impact: "Zero external state dependencies. Simple provider + refresh pattern, no boilerplate.",
    },
    {
      title: "Expo managed workflow over bare RN",
      icon: <Smartphone size={16} />,
      alternatives: "Bare React Native, Native Swift/Kotlin",
      tradeoff: "Managed Expo limits native module access. Some advanced camera/ML features may require ejecting later.",
      decision: "Expo SDK 53 managed workflow covers all requirements: expo-document-picker, expo-clipboard, expo-linear-gradient, expo-font. EAS Build handles CI/CD. OTA updates via expo-updates.",
      impact: "Cross-platform from day one. 4-month delivery timeline met. OTA for post-launch fixes.",
    },
    {
      title: "Custom Animated tab bar over default",
      icon: <Layout size={16} />,
      alternatives: "Expo Router default, react-native-bottom-tabs",
      tradeoff: "Custom implementation means owning the full complexity of touch handling, indicator positioning, and animation reconciliation across screen transitions.",
      decision: "Fully custom with React Native Animated API. Each TabItem manages its own Animated.Value refs. Floating indicator driven by animated translateX. Spring physics (friction: 6, tension: 50) for natural icon transitions.",
      impact: "Signature micro-interaction. Pixel-perfect control. Zero third-party tab bar overhead.",
    },
    {
      title: "SpaceMono single font over multi-font",
      icon: <MessageCircle size={16} />,
      alternatives: "Inter + SpaceMono, custom typeface system",
      tradeoff: "Monospace for all text reduces readability for long passages and limits typographic hierarchy.",
      decision: "SpaceMono provides a clean, modern monospace aesthetic differentiating from typical fantasy apps. One .ttf file minimizes bundle size. Loaded via expo-font on app launch and applied globally through the navigation theme.",
      impact: "Distinctive brand identity. ~60KB font asset. Users associate monospace with data.",
    },
  ],
  challenges: [
    {
      icon: <Activity size={16} />, label: "Nested Scroll + TabView Conflicts",
      problem: "Match detail screen needed a scrollable banner and head-to-head section, followed by a swipeable TabView with 3 tabs. React Native's scroll system conflicts when nesting TabView inside ScrollView.",
      solution: "Combined nestedScrollEnabled=true on inner ScrollViews, scrollEnabled=false on inner FlatLists, overScrollMode='never' on parent. Content height tracked via onContentHeightChange callback. Android version testing essential across API levels.",
      result: "Smooth nested scrolling across all 3 tabs on iOS and Android API 24-35.",
      metrics: ["nestedScrollEnabled", "scrollEnabled=false", "onContentHeightChange"],
    },
    {
      icon: <Cpu size={16} />, label: "Dual Theme System (Safe/Risky)",
      problem: "Safe and risky teams share the same data shape but differ in every visual property — colors, gradients, badges, and buttons must switch between green and orange.",
      solution: "Dynamic theme generator function takes zone as input and returns complete theme object. Two separate components (AiSafeTeam, AiRiskyTeam) with duplicated structure but different theme applications. Acceptable ~100 lines each.",
      result: "Clean green/orange semantic split. Users intuitively understand safe vs risky without explanation.",
      metrics: ["Theme generator", "2 components", "~100 lines each"],
    },
    {
      icon: <Search size={16} />, label: "AI Team Temporal Pairing",
      problem: "Teams are generated in pairs (Safe + Risky) at the same time. Users need to see them grouped together in history, sorted by time, with search.",
      solution: "Generations grouped by minute using createdAt.toISOString().slice(0, 16) as key. Sorted newest-first, limited to 5 pairs. Each pair displays both themes side by side. Search filter by team number or time. ObjectID parsing with try-catch fallback.",
      result: "Clean pair grouping. Search works across 100+ generations without performance issues.",
      metrics: ["ISO minute key", "5 pairs limit", "Defensive parsing"],
    },
    {
      icon: <Image size={16} />, label: "Screenshot Analysis Pipeline",
      problem: "Users upload Dream11 team screenshots for AI analysis. Pipeline must handle file selection, multipart upload, async processing, and structured rendering in one flow.",
      solution: "Single self-contained component (FantasyTracker.jsx) manages entire pipeline: expo-document-picker, FormData multipart upload with userId, loading spinner, key-value results in 2-column grid, strong points extracted from period-delimited API response.",
      result: "Users get AI feedback on actual team selections. Combined upload + analysis pipeline in one component.",
      metrics: ["1 component", "multipart upload", "2-col grid"],
    },
  ],
  techStackTitle: "The tools and frameworks powering Victory Vision",
  techStack: [
    { name: "React Native (Expo SDK 53)", cat: "Mobile", desc: "Cross-platform iOS/Android with Expo Router file-based navigation across 10 screens and 22+ reusable components." },
    { name: "Node.js", cat: "Backend", desc: "REST API with 15+ endpoints for auth (OTP), matches, predictions, AI team generation, screenshot analysis, reports, and notifications." },
    { name: "MySQL", cat: "Database", desc: "Relational data store for users, matches, predictions, teams, analysis results, reports, and notifications." },
    { name: "NativeWind", cat: "UI", desc: "Tailwind CSS utility classes for React Native. Build-time generation eliminates runtime CSS-in-JS overhead across 22+ components." },
    { name: "React Context", cat: "State", desc: "GlobalProviderReport provides match listings, reports, and notifications across 10 screens without Redux. Hydrated on login, refreshed on pull-to-refresh." },
    { name: "Animated API", cat: "Animations", desc: "Custom animated tab bar with spring physics (friction: 6, tension: 50) for icon scale/translateY and timing (400ms) for label fade." },
    { name: "Tab View", cat: "Navigation", desc: "Swipeable tab navigation in match detail screen with 3 tabs. Nested scroll resolution via nestedScrollEnabled + scrollEnabled pattern." },
    { name: "Axios + Moment.js", cat: "Utilities", desc: "Axios for HTTP communication with api.victoryvision.live. Moment.js for date formatting and generation time grouping." },
  ],
  resultsTitle: "Measurable impact from architectural decisions",
  results: [
    { icon: <Smartphone size={20} />, metric: "10", label: "App Screens", desc: "Organized into 2 nav groups (auth, root) with Expo Router file-based routing. Hidden Reports tab accessible programmatically." },
    { icon: <GitBranch size={20} />, metric: "22+", label: "Reusable Components", desc: "Complete design system: cards, tab views, accordions, gradient cards, badges, buttons, and text components." },
    { icon: <Database size={20} />, metric: "15+", label: "API Endpoints", desc: "Node.js REST API covering auth, matches, predictions, AI teams, analysis, reports, and notifications." },
    { icon: <Cpu size={20} />, metric: "AI Teams", label: "Safe + Risky Engine", desc: "Paired generation with dynamic theming, role distribution, win rate projection, and temporal grouping." },
    { icon: <Image size={20} />, metric: "Screenshot AI", label: "Fantasy Analysis", desc: "Multipart upload + AI pipeline. Users upload Dream11 screenshots and get instant structured analysis." },
    { icon: <Layout size={20} />, metric: "Animated Tab Bar", label: "Custom Navigation", desc: "Spring-physics animations, floating indicator, label fade. Zero third-party dependencies." },
  ],
  lessons: [
    { title: "Centralize the API layer into a single Axios instance with interceptors", what: "Create a single Axios instance with request interceptors for auth headers and response interceptors for 401 handling and data normalization, instead of importing Axios directly in every screen.", why: "Each screen handles try-catch, token injection, and error toasts independently. A centralized instance would eliminate ~10 lines of duplicated code per screen and ensure consistent error handling.", impact: "Would remove ~150 lines of duplicated HTTP handling across 15+ screens and guarantee consistent 401 redirect behavior." },
    { title: "Unify Safe/Risky team components into a single themed component", what: "Extract common rendering logic from AiSafeTeam and AiRiskyTeam into a shared presentational component that accepts zone-driven theme props.", why: "The two components share identical structure (~100 lines each) with different theme constants. A unified component with zone prop would eliminate duplication.", impact: "Would reduce ~100 lines of duplicated component code and make it trivial to add new risk levels." },
    { title: "Add periodic background polling for live match updates", what: "60-second background polling during active match hours to refresh lineup changes, toss results, and live prediction updates without pull-to-refresh.", why: "Match data changes infrequently but unpredictably — lineups drop hours before game time. Background polling would keep data fresh without WebSocket complexity.", impact: "Would eliminate manual refresh during match hours and improve prediction accuracy with latest data." },
  ],
  cta: {
    href: "/projects/landsquire",
    icon: <Smartphone size={24} />,
    title: "Land Squire",
    subtitle: "Real Estate Marketplace",
    description: "A full-featured real estate marketplace connecting property buyers, brokers, and bank agents with map-based discovery, bidding, CRM tools, and multi-language support.",
  },
};
