import { Smartphone, Users, Clock, TrendingUp, BookOpen, GitBranch, Activity, Database, Cpu, Zap, Shield, Search, BarChart3, MessageCircle } from "lucide-react";
import type { CaseStudyConfig } from "./types";

export const wealthWalkConfig: CaseStudyConfig = {
  slug: "wealth-walk",
  icon: <TrendingUp size={12} />,
  badgeLabel: "Case Study",
  heroTags: [
    { icon: <Smartphone size={12} />, text: "iOS + Android" },
    { icon: <GitBranch size={12} />, text: "3 Brokers" },
    { icon: <Clock size={12} />, text: "6 Months" },
    { icon: <TrendingUp size={12} />, text: "Fintech" },
  ],
  sections: [
    { id: "story", label: "Story" },
    { id: "experience", label: "Experience" },
    { id: "architecture", label: "Architecture" },
    { id: "decisions", label: "Decisions" },
    { id: "metrics", label: "Metrics" },
    { id: "timeline", label: "Timeline" },
    { id: "challenges", label: "Challenges" },
    { id: "stack", label: "Stack" },
    { id: "results", label: "Results" },
    { id: "lessons", label: "Lessons" },
  ],
  identity: {
    accentFrom: "from-emerald-500/20",
    accentVia: "via-background",
    accentTo: "to-amber-500/5",
    primary: "#059669",
    primaryFaded: "from-emerald-500/10",
  },
  storyTitle: "Retail investors lack institutional-grade tools.",
  storyBody: "Indian retail investors manage portfolios across multiple broker accounts, track market data through separate apps, rely on unverified Telegram groups for trading signals, and lack structured education for financial markets. This fragmentation leads to delayed decisions, untracked performance, and inconsistent learning — while institutional traders have Bloomberg terminals and dedicated analytics teams.",
  storyCoda: "We built the retail investor's command center.",
  flowTitle: "How an Investment Decision Moves",
  flowSteps: [
    { label: "Investor", icon: <Users size={16} /> },
    { label: "Market Data Feed", icon: <Activity size={16} /> },
    { label: "AI Signal Engine", icon: <Cpu size={16} /> },
    { label: "Broker API", icon: <GitBranch size={16} /> },
    { label: "Portfolio Updated", icon: <BarChart3 size={16} /> },
    { label: "Notification", icon: <MessageCircle size={16} /> },
    { label: "Investor", icon: <Users size={16} /> },
  ],
  features: [
    {
      id: "dashboard", number: "01", icon: <Activity size={14} />, label: "Dashboard", title: "Live Market Dashboard",
      tagline: "Real-time portfolio and market overview",
      problem: "Retail investors jump between broker apps, market data sites, and signal groups to understand their positions and market direction.",
      solution: "A unified home screen with real-time portfolio value, P&L tracking, market indices (NIFTY, Sensex, FX), recent trades, and AI-curated market news — all in a single scrollable feed.",
      metrics: "Real-time P&L | Market indices | AI-curated news",
    },
    {
      id: "portfolio", number: "02", icon: <BarChart3 size={14} />, label: "Portfolio", title: "Multi-Broker Portfolio Tracking",
      tagline: "All your holdings, one place",
      problem: "Users with accounts across Zerodha, Angel, and Upstox had no unified view of their total exposure, sector allocation, or net performance.",
      solution: "Broker-agnostic portfolio sync with holdings, positions, and trade history aggregated from multiple accounts. Sector-wise allocation, concentration risk metrics, and performance attribution across timeframes.",
      metrics: "Multi-broker sync | Sector allocation | Performance attribution",
    },
    {
      id: "signals", number: "03", icon: <Zap size={14} />, label: "AI Signals", title: "AI Trading Signals",
      tagline: "Explainable, not black-box",
      problem: "Telegram signal groups provide buy/sell calls with no track record, no explainability, and zero accountability — users trust blindly or not at all.",
      solution: "AI-generated trading signals with confidence scores, supporting rationale, and backtested performance. Signals segmented by asset class (equity, derivatives, FX). Free tier for discovery, paid subscription for premium signals with live alerts.",
      metrics: "Explainable AI | Confidence scores | Free + Premium tiers",
    },
    {
      id: "discovery", number: "04", icon: <Search size={14} />, label: "Discovery", title: "Smart Stock Discovery",
      tagline: "Screeners, patterns, and AI picks",
      problem: "Finding trading opportunities requires scanning hundreds of stocks across multiple screeners, charts, and news sources.",
      solution: "Multi-criteria stock screener with category-wise browsing, AI pattern recognition on charts (bullish/bearish patterns with confidence), and algorithmic screeners for pre-built strategies like momentum, mean reversion, and breakout detection.",
      metrics: "Multi-criteria screener | AI pattern detection | Pre-built strategies",
    },
    {
      id: "algo", number: "05", icon: <Cpu size={14} />, label: "Algo Trading", title: "Algorithmic Strategy Engine",
      tagline: "Deploy strategies without coding",
      problem: "Algorithmic trading requires programming skills. Retail investors who understand strategy concepts can't implement them without developers.",
      solution: "Pre-built strategy templates (momentum, mean reversion, options selling) that users configure via simple parameters — entry conditions, position sizing, stop-loss rules. Strategies run on cloud servers with 99.9% uptime. Live monitoring dashboard with running/stopped status.",
      metrics: "Pre-built templates | Parameter config | Cloud execution",
    },
    {
      id: "education", number: "06", icon: <BookOpen size={14} />, label: "Education", title: "Structured Learning Path",
      tagline: "From basics to algorithmic trading",
      problem: "Learning trading is fragmented — YouTube for basics, paid courses for advanced, no structured path from beginner to algorithmic trader.",
      solution: "A complete curriculum organized into category-wise courses with video lessons, articles, and quizzes. Track progress per course. Content ranges from 'What is a stock?' to 'Building your first trading algorithm.'",
      metrics: "Category-wise courses | Video + Articles | Progress tracking",
    },
    {
      id: "broker", number: "07", icon: <GitBranch size={14} />, label: "Broker", title: "Broker Connection & Order Flow",
      tagline: "Connect, trade, track",
      problem: "Executing an AI signal required: read signal → open broker app → search symbol → place order. Break in context, delay in execution.",
      solution: "In-app broker connection flow with guided setup, real-time connection status, and one-tap order placement directly from signal details. Order book with executed/pending/open views. Full trade history with P&L per trade.",
      metrics: "In-app order placement | Order book | Full trade history",
    },
  ],
  metrics: [
    { icon: <Smartphone size={16} />, value: 40, suffix: "+", label: "Screens", sublabel: "Across app + admin panel", color: "text-accent" },
    { icon: <Database size={16} />, value: 35, suffix: "+", label: "API Endpoints", sublabel: "Node.js REST API", color: "text-emerald-400" },
    { icon: <GitBranch size={16} />, value: 3, suffix: "", label: "Broker Integrations", sublabel: "Zerodha, Angel, Upstox", color: "text-accent" },
    { icon: <Activity size={16} />, value: 3, suffix: "+", label: "Market Data Providers", sublabel: "Real-time streaming", color: "text-cyan-400" },
    { icon: <Cpu size={16} />, value: 2, suffix: "", label: "ML Models", sublabel: "Ensemble (GBM + NN)", color: "text-emerald-400" },
    { icon: <BarChart3 size={16} />, value: 6, suffix: "mo", label: "Dev Timeline", sublabel: "Concept to launch", color: "text-accent" },
  ],
  timelineTitle: "6 months from concept to launch",
  timeline: [
    { phase: "1", title: "Discovery & Architecture", desc: "Market research with 50+ retail investors, competitor analysis, system architecture design, data model planning" },
    { phase: "2", title: "Auth & Core Infrastructure", desc: "Firebase auth, Node.js API gateway, PostgreSQL schema, Redis caching layer, Docker containerization" },
    { phase: "3", title: "Market Data Pipeline", desc: "Real-time market data ingestion from multiple providers, WebSocket distribution, Redis pub/sub for live updates" },
    { phase: "4", title: "AI Signal Engine", desc: "Python ML service with ensemble models, SHAP explainability, and signal generation pipeline" },
    { phase: "5", title: "Broker Integration", desc: "API integration with 3 major Indian brokers, order placement flow, position sync, trade reconciliation" },
    { phase: "6", title: "Education & Premium", desc: "Course content creation, subscription management, payment integration, admin panel for content management" },
    { phase: "7", title: "Testing & Launch", desc: "Load testing (1K concurrent users), security audit for financial data compliance, app store submission" },
  ],
  decisions: [
    {
      title: "Python ML service over Node.js for AI signals",
      icon: <Cpu size={16} />,
      alternatives: "Node.js TensorFlow.js, external AI API",
      tradeoff: "Python microservice adds infrastructure complexity — separate deployment, monitoring, and inter-service communication overhead.",
      decision: "Python's ML ecosystem (TensorFlow, scikit-learn, pandas) provides superior model training, evaluation, and explainability tools. The ML service runs as a separate Docker container communicating via REST with the Node.js API gateway. This isolates AI computation from user-facing API traffic.",
      impact: "Isolated scaling: ML service scales independently from API traffic. Easy to swap models without touching the application layer.",
    },
    {
      title: "PostgreSQL over MongoDB for financial data",
      icon: <Database size={16} />,
      alternatives: "MongoDB, MySQL, TimescaleDB",
      tradeoff: "Document stores offer schema flexibility but financial data has well-defined schemas and requires strict relational integrity (transactions, accounts, orders).",
      decision: "PostgreSQL with JSONB columns for semi-structured data (signal metadata, user preferences). ACID compliance guarantees no lost trades or double-executions. Well-defined schemas for orders, portfolios, and subscriptions.",
      impact: "ACID compliance maintained. JSONB provides flexibility where needed. Well-defined schemas for financial data.",
    },
    {
      title: "Feature flags over separate dev/staging environments",
      icon: <GitBranch size={16} />,
      alternatives: "Full staging environment, branch-based deployments",
      tradeoff: "Feature flags in production risk exposing unfinished features. Staging environments can drift from production configuration.",
      decision: "LaunchDarkly feature flags enable gradual rollout of new signals, subscription tiers, and broker integrations. Kill switches for emergency disabling of faulty features without deployment. Environment parity reduces 'works on staging' bugs.",
      impact: "Smooth rollouts. Emergency kill switch used twice for market data provider outages.",
    },
    {
      title: "In-app order flow over deep linking to broker apps",
      icon: <Smartphone size={16} />,
      alternatives: "Deep linking to broker apps, WhatsApp-based order relay",
      tradeoff: "In-app order execution requires broker API integration and security compliance. Deep linking is simpler but breaks the user flow.",
      decision: "Direct broker API integration for one-tap order placement from signals, screeners, and portfolio screens. Users never leave the app. OAuth-based broker connections with encrypted credential storage.",
      impact: "Higher signal-to-trade conversion vs deep linking approach. Users complete trades without leaving the app.",
    },
  ],
  challenges: [
    {
      icon: <Activity size={16} />, label: "Real-Time Market Data at Scale",
      problem: "Delivering sub-second market data updates to many concurrent users while maintaining availability during market hours. NIFTY, Sensex, FX pairs, and individual stock prices update simultaneously.",
      solution: "WebSocket connections managed through a connection pool. Redis pub/sub distributes incoming data to all connected clients. Data ingestion runs as a separate service that normalizes feeds from multiple providers before publishing to Redis.",
      result: "Streaming delivery via WebSocket + Redis pub/sub. Data normalized from multiple providers. Auto-scaled during market hours.",
      metrics: ["WebSocket push", "Redis pub/sub", "Auto-scaling"],
    },
    {
      icon: <Shield size={16} />, label: "Financial Data Security & Compliance",
      problem: "Broker credentials and trade data require bank-grade security. Storing API keys, tokens, and financial positions on-device and on-server.",
      solution: "AES-256 encryption at rest for all financial credentials. Encrypted local storage on device via react-native-encrypted-storage. Server-side encryption keys rotated every 30 days. All API traffic over TLS 1.3.",
      result: "Encrypted storage at rest and on-device. TLS 1.3 for all traffic. Key rotation schedule.",
      metrics: ["AES-256", "30-day key rotation", "TLS 1.3"],
    },
    {
      icon: <Cpu size={16} />, label: "ML Model Accuracy & Explainability",
      problem: "Trading signals need both accuracy AND human-readable explanations. A black-box model is useless if users can't understand why a signal was generated.",
      solution: "Ensemble model combining gradient boosting (GBM) for price direction prediction with SHAP values for feature importance explanation. Each signal output includes top 3 contributing factors (e.g., 'RSI oversold', 'Volume surge').",
      result: "SHAP-based explainability. Top 3 contributing factors per signal. Ensemble approach improves robustness over single models.",
      metrics: ["Ensemble GBM + NN", "SHAP explanations", "Top-3 factors"],
    },
    {
      icon: <GitBranch size={16} />, label: "Broker API Fragmentation",
      problem: "Each Indian broker has a different API — different auth flows, order formats, rate limits, and reliability characteristics. Supporting 3 brokers means 3 separate integrations with ongoing maintenance.",
      solution: "Broker abstraction layer with adapter pattern. Common interface (connect, getPositions, placeOrder, getHistory) with broker-specific adapters implementing the details. Exponential backoff for rate limits. Webhook-based position sync where available.",
      result: "3 broker integrations completed in 5 weeks. Adding a new broker takes ~2 weeks. Consistent error handling across all brokers.",
      metrics: ["3 brokers", "5 weeks integration", "2 weeks per new broker"],
    },
  ],
  techStackTitle: "The tools and frameworks powering Wealth Walk",
  techStack: [
    { name: "React Native", cat: "Mobile", desc: "Cross-platform iOS/Android app with 40+ screens across user-facing app and admin panel. Real-time data via WebSocket." },
    { name: "Node.js + Express", cat: "Backend", desc: "API gateway with 35+ REST endpoints. Routes requests to domain services: market data, AI signals, broker integration, user management." },
    { name: "Python + TensorFlow", cat: "ML", desc: "Ensemble ML model (gradient boosting + neural network) for trading signal generation. SHAP explainability. Runs as isolated Docker microservice." },
    { name: "PostgreSQL", cat: "Database", desc: "Primary data store with ACID compliance for financial transactions. JSONB columns for flexible signal metadata and user preferences." },
    { name: "Redis", cat: "Infrastructure", desc: "Session caching, real-time market data pub/sub distribution, and AI response caching with TTL-based invalidation." },
    { name: "Docker + AWS", cat: "DevOps", desc: "Containerized microservices deployed on AWS ECS. Auto-scaling for WebSocket servers during market hours. CloudFront CDN for static assets." },
    { name: "Firebase", cat: "Infrastructure", desc: "Authentication (email + Google OAuth), push notifications for trade alerts and signal delivery, and analytics for user engagement tracking." },
    { name: "Socket.IO + WebSocket", cat: "Real-Time", desc: "Bidirectional communication for live portfolio updates, market data streaming, and real-time signal delivery to connected clients." },
  ],
  resultsTitle: "Measuring what we built",
  results: [
    { icon: <Smartphone size={20} />, metric: "40+", label: "Screens", desc: "React Native screens across the mobile app and admin panel. Role-aware navigation for investors, admins, and content managers." },
    { icon: <Database size={20} />, metric: "35+", label: "API Endpoints", desc: "Node.js + Express REST API serving market data, AI signals, portfolio aggregation, broker integration, and subscriptions." },
    { icon: <Cpu size={20} />, metric: "2", label: "ML Models", desc: "Ensemble model (gradient boosting + neural network) for signal generation. SHAP explainability produces human-readable rationales." },
    { icon: <GitBranch size={20} />, metric: "3", label: "Broker APIs", desc: "Adapter-based broker abstraction for Zerodha, Angel, and Upstox. Common interface pattern allows adding new brokers in ~2 weeks." },
    { icon: <Activity size={20} />, metric: "3+", label: "Market Data Feeds", desc: "Real-time data ingestion from multiple providers. WebSocket push via Redis pub/sub. Auto-scaling during market hours." },
    { icon: <Clock size={20} />, metric: "6 mo", label: "Development", desc: "Concept to launch in 6 months. 7-phase timeline covering infrastructure, ML pipeline, broker integration, and content platform." },
  ],
  lessons: [
    { title: "Financial data requires bank-grade security posture from day one", what: "Implement encrypted local storage, server-side encryption with rotation, and TLS 1.3 before the first API call — not as a compliance afterthought.", why: "Financial credentials and trade data are high-value targets. Retrofitting encryption is exponentially harder than building with it. We spent significant time retrofitting encrypted storage after the initial build.", impact: "Would have saved development time and eliminated security findings in the first audit." },
    { title: "Explainable AI is non-negotiable for financial decision support", what: "Invest in SHAP/LIME explainability infrastructure alongside model training, not after. Every signal output should include top contributing factors in plain language.", why: "Users rejected early black-box signals despite strong accuracy. Trust requires understanding. Adding SHAP explanations increased signal adoption significantly.", impact: "Higher signal adoption rate when users understand the rationale behind signals." },
    { title: "Real-time data architecture differs fundamentally from request-response", what: "Design for streaming from the start: WebSocket connection pool, Redis pub/sub distribution, client-side buffering for reconnection gaps.", why: "The initial REST polling approach caused 200K+ DB reads/minute during market hours with stale data between polls. Migrating to WebSocket + pub/sub reduced DB load by 95% and improved data freshness from seconds to milliseconds.", impact: "95% reduction in DB reads. Data freshness improved from 5-second polls to <50ms streaming." },
  ],
  cta: {
    href: "/projects/victory-vision",
    icon: <Cpu size={24} />,
    title: "Victory Vision",
    subtitle: "Fantasy Sports Intelligence",
    description: "AI-powered fantasy sports companion with team generation, screenshot analysis, match predictions, and performance tracking. Built with React Native (Expo SDK 53).",
  },
};
